export const members = [
    {
      name: "Marvin Abernathy",
      lastname: "Lynch",
      position: "Legacy Factors Manager",
      id: "9",
    },
    {
      name: "Dr. Otis Bernhard",
      lastname: "Robel",
      position: "Regional Accountability Facilitator",
      id: "10",
    },
    {
      name: "Jason Zieme",
      lastname: "Nitzsche",
      position: "Central Markets Executive",
      id: "11",
    },
    {
      name: "Lana Gerhold",
      lastname: "Zieme",
      position: "District Branding Associate",
      id: "12",
    },
    {
      name: "Vincent Mertz DDS",
      lastname: "Kilback",
      position: "Internal Communications Officer",
      id: "13",
    },
    {
      name: "Mr. Paul Cormier",
      lastname: "Reichel",
      position: "Dynamic Functionality Facilitator",
      id: "14",
    },
    {
      name: "Allen Kessler",
      lastname: "Yost",
      position: "Direct Division Consultant",
      id: "15",
    },
    {
      name: "Taylor Dicki-Stamm",
      lastname: "Rodriguez",
      position: "Lead Response Specialist",
      id: "16",
    },
    {
      name: "Marshall Satterfield III",
      lastname: "Connelly",
      position: "Senior Communications Representative",
      id: "17",
    },
    {
      name: "Lynn Thompson",
      lastname: "Steuber",
      position: "Dynamic Group Planner",
      id: "18",
    },
    {
      name: "Emma Langworth",
      lastname: "Upton",
      position: "Product Brand Representative",
      id: "19",
    },
    {
      name: "Alejandro Kirlin",
      lastname: "Hodkiewicz",
      position: "Investor Program Developer",
      id: "20",
    },
    {
      name: "Jose",
      lastname: "Mujica",
      position: "Guerrilla, Farmer and former President of Uruguay",
      id: "21",
    },
    {
      name: "Tom Cat",
      lastname: "Berge",
      position: "Principal Factors Planner",
      id: "22",
    },
  ];